### ISSUE TITLE
Importing XEL files

### ISSUE THREAD

**Issue by naveenrpendli** [microsoft/SqlNexus#103]
I started to use this tool and having an issue with importing extended events files into Nexus. All the documentation is talking about the visualization but I really haven't found the file types it supports. Another issue is that can I have data collected through my custom T-SQL scripts and visualize it from the DB that I created for nexus ?, Please guide me on this one.

Thanks
Naveen

**Comment by suresh-kandoth** [comment]
try running ReadTrace.exe to process the XEL files. Here are the parameters to use:

-I  File name of the first .TRC or .XEL file to process [REQUIRED].
-i  If specified, indicates that the .TRC file(s) to process are present inside a CAB/ZIP/RAR file with this file name
-o  Full path of directory to place output files [default is current directory]
-S  Name of SQL Server 2005 server to connect to when loading performance analysis data [default is (local)]
-d  Database to use when loading performance data [default is PerfAnalysis].
    User specified below must have CREATE DATABASE permission (if DB doesn't
    exist) or be part of the db_owner role if the database already exists.
-E  Connect to SQL using Windows Authentication [default]
-U  Connect to SQL using this user name
-P  Password for the user specified in -U option
-a  Disable performance analysis
-f  Do not produce .RML output files for each Session and Request
-Q  Do normalization parse using quoted_identifier OFF symantics.  (Default is ON)
-F  File name containing the normalize filter matches
-r# Read at most this # of files (including the first) [default is all files
    until a break in the rollover file sequence is detected].
-M  Mirror trace events by Session to the specified output directory (All Sessions
    will be output even if Session filter is specified)
-MF Mirror trace events by Session to the specified output directory (Only Sessions
   matching filter parameters will be output)
-MS Mirror trace events to a single .TRC file in the specified output directory.
-M[FS] or -M[SF] Combine mirror filtering with single .TRC file output
    *** NOTE: The mirroring option may be overwritten because the source metadata information indicates such a change. ***
-A  'INCLUDE or EXCLUDE' events with Application Names
-C  'INCLUDE or EXCLUDE' events with Database Names when possible
-H  'INCLUDE or EXCLUDE' events with Host Names
-s# 'INCLUDE or EXCLUDE' events from specified Sessions
-X# 'INCLUDE or EXCLUDE' events based on Event Class value
-x# 'INCLUDE or EXCLUDE' events based on SubClass value
-B### Time bias: Adjusts the start and end times, as read by (+-)### minutes.
-b  Provide a designated start time in required format 2000-05-25 11:46:20:060
-e  Provide a designated stop time in required format  2000-05-25 11:46:20:060
-D  Skip date on log file output
-L  Integer value representing the language id
-Y  Optional scratch path used by Expander when handling compressed files.  If you processing lots of files from a nested archive this can increase performance.
-?  Show usage of command line parameters

EXAMPLES:
ReadTrace -Iserver__sp_trace.trc -ic:\temp\traces.cab -oc:\temp\output -f
ReadTrace -I"c:\my traces\80AllEvents.trc" -o"c:\my output"
ReadTrace -Ioutput\SQLSRV1__sp_trace_20.trc -ic:\temp\pssdiag.zip -oc:\temp\breakout -f -r2
