### ISSUE TITLE
Invalid Object Name tblDefaultConfigures when connecting via 'sa'

### ISSUE THREAD

**Issue by ReplTalk** [microsoft/SqlNexus#107]
![image](https://user-images.githubusercontent.com/28520891/112196729-b675ad80-8be1-11eb-9de5-368861b113a0.png)

**Comment by PiJoCoder** [comment]
No repro of this yet @ReplTalk . Please let me know if the build I sent to you for testing fixes this?

**Comment by PiJoCoder** [comment]
This was likely happening due to the object not being created when using SA authenticaiton. This was fixed in #108 . So closing. Please reopen if you can repro again
