### ISSUE TITLE
Head blocker trigger not showing on Nexus Tables

### ISSUE THREAD

**Issue by asavioli** [microsoft/SqlNexus#110]
After collecting data with pssdiag and loading it into nexus, I noticed the following issue:

1 - On the perfstat raw file, a trigger is showing as head blocker frequently

2 - On the table tbl_HEADBLOCKERSUMMARY generated by nexus, the trigger is no there.

![raw_file](https://user-images.githubusercontent.com/49494532/113116928-dae71080-9205-11eb-8150-2ce732bb3ebb.jpg)
![nexus_table](https://user-images.githubusercontent.com/49494532/113116932-db7fa700-9205-11eb-8df6-b2ac5a100501.jpg)

**Comment by PiJoCoder** [comment]
This was fixed in 025bca55e8a5deac2c95c2494d58f9067d50d189 and related to #113
