### ISSUE TITLE
WaitStatsreporttemplate.pbit not found

### ISSUE THREAD

**Issue by khaliljamil** [microsoft/SqlNexus#111]
Could you please share the PBI template 'SqlNexus-7.21.03.26\NexusReports\WaitStatsreporttemplate.pbit' not found in the solution code.

Thank you.

**Comment by ram2ybabu** [comment]
@khaliljamil - It seems the file 'WaitStatsreporttemplate.pbit' is included accidentally in the report, it doesn't really contain anything. I have deleted this now and you don't find in the upcoming releases.
