### ISSUE TITLE
Update links in Best Practices

### ISSUE THREAD

**Issue by gambit9009** [microsoft/SqlNexus#118]
Several links given in the Url column are no longer active.  http://aka.ms/batchsort is an example that ends up forwarding you to https://devblogs.microsoft.com/.  Others act the same...need to check and correct all.

**Comment by PiJoCoder** [comment]
Also use the newly updated TF article with direct reference to TF info e.g. [TF2340](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql?view=sql-server-ver15#tf2340) 
@jpolisel

**Comment by PiJoCoder** [comment]
Fixed in these commits: 
7c1134d14b0a36af949ac9af7b90f895995c5b3f
a6a1b51fe701a1ab23a339121fdb6e34cc1b1741
