### ISSUE TITLE
Can not display repors

### ISSUE THREAD

**Issue by TakwaM** [microsoft/SqlNexus#121]
![image](https://user-images.githubusercontent.com/85371441/121526809-ab1c6c00-c9f1-11eb-8c01-e18d46953024.png)
![image](https://user-images.githubusercontent.com/85371441/121526849-b53e6a80-c9f1-11eb-9c66-53e40f7d5bae.png)
Hello, I have trouble visualizing reports after running SQLNExus Analyses, some reports are not available. 
Can any one help me understand what could be the issue

**Comment by skh1000** [comment]
I also have this issue -- but I'm very new, not sure I'm specifying the instance everywhere I need to.  I am able to import data ok, though, so I'm doing something right, but have yet to get a report to work.

**Comment by PiJoCoder** [comment]
Yes, SQL Nexus will show you only reports for the data you collected. If this data was not collected originally via tools like PSSDIAG or SQL LogScout, the data cannot be reported and thus cannot be visualized in reports. In this case the pal_Counters table is missing. I believe this data is generated from Perfmon data.

**Comment by PiJoCoder** [comment]
Discovered what the issue was. It was a half-baked feature in SQLNexus that didn't work. Removed references to that report.
