### ISSUE TITLE
invalid object name 'dbo.tbl_ServerProperties' bug

### ISSUE THREAD

**Issue by skh1000** [microsoft/SqlNexus#124]
Doing one of the performance reports gets this error (sorry, can't get text)

![image](https://user-images.githubusercontent.com/91285297/134565581-77773d5c-103e-447b-bd56-357dbac6e99d.png)

This seems to happen in versions 7_21_07_07 as well as 7_21_03_26.
Anyone?

**Comment by PiJoCoder** [comment]
In some cases the tbl_ServerProperties table data may not have been there in the original data you imported. It depends on what data you captured or maybe during your data capture you had a failure? That able is imported from teh --ServerProperty-- output in the *_MiscPssdiagInfo.out file collected by PSSDIAG
