### ISSUE TITLE
SQL Nexus - Bottleneck analysis showing 100% cpu usage when it's not the case

### ISSUE THREAD

**Issue by olivieraupetit** [microsoft/SqlNexus#126]
In SQL Server Bottle neck analysis, the graph showing System CPU Utilization displays 100% CPU for sql server cpu utilisation (red bars)

![nexusgraph](https://user-images.githubusercontent.com/23724875/139108089-e3f6f178-b43f-4652-8202-e514722fecd9.jpg)

But checking BLG files we can see total CPU usage is far from 100% (40% on average) 
	                               
![perfmonview](https://user-images.githubusercontent.com/23724875/139108124-0fd08e45-690b-4dec-a2c1-70f760b23d5a.jpg)

and the same values are also reported in Perfmon Summary

![nexusperfmonsummary](https://user-images.githubusercontent.com/23724875/139107990-b62efebb-0513-4d8a-8d70-8a0bd7ef3faa.jpg)

Note: we have 32 processors on the machine where PSSDIAG was run

**Comment by PiJoCoder** [comment]
@olivieraupetit , this should be now addressed with the [latest release 7.22.11.11](https://github.com/microsoft/SqlNexus/releases/tag/7.22.11.11). Fixed in https://github.com/microsoft/SqlNexus/issues/193
