### ISSUE TITLE
SQL Nexus errors on headblockers, and CPU view with no data

### ISSUE THREAD

**Issue by link11516** [microsoft/SqlNexus#134]
Hi team,

I just noticed that on SQL Nexus 7.22.02.16 we have the following issue:

When we go to the "Blocking and Wait Statistics" section and click on any blocking chain, we will have the following error:

"The "BlockingChainRowNum" parameter is missing a value at Microsoft.Reporting.WinForms.RSParams.ValidateReportInputs.Satisfied() at Microsoft.Reporting.WinForms.ReportViewer.RenderReportWithNewParameters(int32 pageNumber, PostRenderArgs postRenderArgs)"

And also when going to "Bottleneck Analysis" the "System CPU Utilization" is with no data.

I double checked this and other peers have the same situation with same version.

Thanks team!

**Comment by PiJoCoder** [comment]
Got more information on this from @link11516 . Here is the error screen

![image](https://user-images.githubusercontent.com/23519517/154890677-6033dd9f-897f-42f2-8e97-23d5aa9c1805.png)

**Comment by PiJoCoder** [comment]
still some corner cases there that need fixing...
