### ISSUE TITLE
Switch SQL Nexus to using the NuGet package and remove the installation prerequisite on ReportViewer

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/SqlNexus#140]
If we start using NuGet consistently and ship the ReportViewer DLLs with SQLNexus, we can eliminate the need for pre-installing ReportViewer control. Plus for security and accessibility improvements go to the latest version https://www.nuget.org/packages/Microsoft.ReportingServices.ReportViewerControl.Winforms

1. Get the Nuget package
Tools->Nuget Package Manager -> Package Manager Console
`PM> NuGet\Install-Package Microsoft.ReportingServices.ReportViewerControl.Winforms -Version 150.1586.0`
2. Build SQL Nexus and this will ship the DLLs inside the \SQLNexus folder

**Comment by PiJoCoder** [comment]
We should check if we can do this for CLR Types as well and thus we will remove that as a prerequisite installation too.

**Comment by PiJoCoder** [comment]
We are already doing that currently. Will test on several system and ask folks to test next.

**Comment by moraja** [comment]
cbea643fe7f98c1eca8502ba8674fddfc16c9a7e

018b6767ed210c3e1d09a5295e387bdbbcf9d4c4

8c8a900555e9f4e7b3dd7abdb836adf7a2038516
