### ISSUE TITLE
Create, Clean-up/deduplicate AG-related XML rowsets in the RowsetImportEngine\TextRowset.xml

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/SqlNexus#157]
These rowsets are not really defined with columns. But also for **tbl_availability_groups** there is already a rowset defined

- There is one defined for this, so delete this:
```
    <Rowset name="tbl_availability_groups" enabled="true" identifier="--sys.availability_groups--" type="RowsetImportEngine.TextRowset">
    </Rowset>
```

- Define this one if needed and make sure there is data collected for it in PSSDIAG/SQL LogScout
```
    <Rowset name="tbl_dm_hadr_availability_replica_states" enabled="true" identifier="--sys.dm_hadr_availability_replica_states--" type="RowsetImportEngine.TextRowset">
    </Rowset>

- There is another one defined for it, so delete this: 
```   
    <Rowset name="tbl_availability_replicas" enabled="true" identifier="--sys.availability_replicas--" type="RowsetImportEngine.TextRowset">
    </Rowset>

See related on the data collection side: https://github.com/microsoft/DiagManager/issues/162

**Comment by gambit9009** [comment]
Table defs....

https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-hadr-availability-replica-states-transact-sql?msclkid=f21c6f28c1cc11ecbe0eaec0f6c3b920&view=sql-server-ver15

https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-availability-groups-transact-sql?msclkid=04339893c1cd11ec90e7100f700dd282&view=sql-server-ver15

https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-availability-replicas-transact-sql?view=sql-server-ver15#:~:text=sys.availability_replicas%20%28Transact-SQL%29%20%20%20%20Column%20name%20,SQL%20Serve%20...%20%2018%20more%20rows%20?msclkid=f4bbefc0c1cd11ec97deb80f851a81b6

**Comment by PiJoCoder** [comment]
Fixed in:
00119a647a46a810c60e953bdd0611bc61d9bd8e
f315c008ce582414664fc469f8cc85e72b730815
