### ISSUE TITLE
Work to do:  Merge Linux PR 139

### ISSUE THREAD

**Issue by gambit9009** [microsoft/SqlNexus#160]
Needs some manual checks to get the Linux project merged.  Handful of conflicts but didn't look like a major effort.

https://github.com/microsoft/SqlNexus/pull/139

**Comment by PiJoCoder** [comment]
Updated the Linux branch with latest Master changes and resolved conflicts: 
d73e64d1e26cde75a6ba028305a60d86c1368005
07a2578ba70c30b2fac5861d99a7ca60fb31def1
0e4e0f5f103397c6715af887a548ffaca2f81b84

**Comment by gambit9009** [comment]
Done
