### ISSUE TITLE
Rename folder or do something with NexusReports folder

### ISSUE THREAD

**Issue by gambit9009** [microsoft/SqlNexus#163]
There are several folders with reports...

....SqlNexus\NexusReports
....SqlNexus\sqlnexus\Reports
also backup folder and backup files have ended up in the source.

If/when you build you end up with 
SqlNexus\sqlnexus\bin\Debug\Reports
SqlNexus\sqlnexus\bin\Release\Reports

and of course outside of any dev work, any other place SQL Nexus is run from it will have the Reports folder

The prebuild.cmd batch file is copying the RDL files from "SqlNexus\NexusReports" into the "Reports" folder depending on how you are building/running and renames them to RDLC.  

Every time I have to get in to tshoot these I get confused.  LOL.   We could rename the NexusReports folder to SourceReports...or something

**Comment by PiJoCoder** [comment]
I attempted to rename folders but this breaks several dependencies. Also the NexusReports project is not easily accessible to modify its properties. For now moving this to a later Wave for consideration.
