### ISSUE TITLE
Blank and missing Reports 

### ISSUE THREAD

**Issue by v-pamngum** [microsoft/SqlNexus#164]
The bottleneck Analysis report comes up blank. I have experienced this about 4 times after importing different customer data. Secondly, I have also experienced several occasions of missing ReadTrace reports

**Comment by PiJoCoder** [comment]
@v-pamngum can you provide examples for reproducing the problem. Typically reports would be blank if data is not captured and there is nothing to be shown. Another reason could be the RML utilities (ReadTrace.exe) failed to import (make sure you get the latest version -https://github.com/Microsoft/SqlNexus/wiki/RML-Utility)  . Examine the logs in SQL Nexus to see if you can understand the problem yourself
