### ISSUE TITLE
Add columns in TextRowsets.xml for sys.dm_tran_persistent_version_store_stats and sys.dm_tran_aborted_transactions

### ISSUE THREAD

**Issue by gambit9009** [microsoft/SqlNexus#168]
PSSdiag issue #44 (https://github.com/microsoft/DiagManager/issues/44) is adding these tables.

select * From sys.dm_tran_persistent_version_store_stats
select * From sys.dm_tran_aborted_transactions

Add those columns in Nexus

**Comment by gambit9009** [comment]
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-tran-aborted-transactions?view=sql-server-ver16
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-tran-persistent-version-store-stats?view=sql-server-ver16

**Comment by PiJoCoder** [comment]
tested
