### ISSUE TITLE
In PSSDiag, added or renamed some columns in  TempDB and Trans collector.  Need to update TextRowset.xml

### ISSUE THREAD

**Issue by gambit9009** [microsoft/SqlNexus#170]
Also for **sys.index_resumable_operations**

https://github.com/microsoft/DiagManager/issues/150

Different DMVs but same issue...
https://github.com/microsoft/SqlNexus/issues/168

**Comment by PiJoCoder** [comment]
Added rowsets. Need to fix on PSSDIAG side and test

**Comment by PiJoCoder** [comment]
Tested successfully.
