### ISSUE TITLE
Create new reports for Always On Datasets

### ISSUE THREAD

**Issue by hacitandogan** [microsoft/SqlNexus#172]
new AG datasets imported into SQL nexus database as part of issue #167 
Create new reports to show this information on Nexus.

**Comment by hacitandogan** [comment]
@PiJoCoder , once you have the time ,could you please review these new reports and share your comments /feedbacks for any modifications / improvements ?

**Comment by PiJoCoder** [comment]
One commit associated with this issue: 8f11d3b
