### ISSUE TITLE
including additon info for database (Chirag)

### ISSUE THREAD

**Issue by jackli2000** [Microsoft/SqlNexus#18]
Database Size (and Used Space)
Auto Growth Settings for data and log files
Database Compatibility Level 
VLF count

**Comment by shahchi1** [comment]
Currently PSSDiag, does not tell us how big is database..?

Can we include this important info...?

Chirag Shah (MSFT)

**Comment by vikasrana2006** [comment]
You can pull database size using following query:
select * from [dbo].[tbl_SPHELPDB] where dbid>0

Query following table to get file level detail 

select * from [dbo].[tbl_DatabaseFiles]
