### ISSUE TITLE
Availability Group Best Practice Checks

### ISSUE THREAD

**Issue by JamesFerebee** [microsoft/SqlNexus#196]
Add Best Practices report section to:

1) Check if hadr endpoint is enabled/running. If not, flag it.
2) Report if any databases in an AG are showing unhealthy. If so, flag it. (see AG dashboard for reference)

**Comment by PiJoCoder** [comment]
Possibly query to use:

`SELECT dc.database_name, d.synchronization_health_desc, d.synchronization_state_desc, d.database_state_desc From sys.dm_hadr_database_replica_states d JOIN sys.availability_databases_cluster dc ON d.group_database_id = dc.group_database_id AND d.is_local = 1`

**Comment by PiJoCoder** [comment]
```sql
SELECT group_name, 
  operational_state_desc, 
  connected_state_desc, 
  synchronization_health_desc
FROM tbl_hadr_ag_replica_states

SELECT 
  name as AG_Name, 
  synchronization_health_desc 
FROM tbl_hadr_ag_states

SELECT 
  name as HADR_Endpoint, 
  type_desc, 
  state_desc 
FROM tbl_hadr_endpoints_principals
```
