### ISSUE TITLE
Zip file being blocked by Edge?

### ISSUE THREAD

**Issue by dwainew** [microsoft/SqlNexus#231]
MS Edge is identifying the SQLNexus_f_7_22_11_11_Signed.zip as "isn't commonly downloaded."  My organization doesn't allow the "keep it" function, so I simply can't get to it.

![2023-05-03_11-26-05](https://user-images.githubusercontent.com/6252957/235964123-22b7b46b-e02d-435f-822c-3b753ce49fac.png)

is it possible for someone to work with the edge team to prevent this from happening to signed Microsoft files?

**Comment by PiJoCoder** [comment]
Thanks @dwainew for reporting this. I have submitted a request to review the file with Microsoft Security Intelligence and have indicated that it is incorrectly reported.

Appreciate your patience as that team reviews the information.

**Comment by PiJoCoder** [comment]
@dwainew , this seems to be resolved now after submitting the file to https://www.microsoft.com/en-us/wdsi/filesubmission. 

Thank you for reporting it to help everyone benefit.
