### ISSUE TITLE
Expose custom queries and/or the report queries in SQL Nexus so users can customize their data mining

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/SqlNexus#239]
1. Perhaps put a link to https://github.com/microsoft/SqlNexus/wiki/Reports-via-SQL-Queries on the main page report when SQL Nexus launches
2. Expose the query text for the report in each query. We can do this by creating TextBox in every report and displaying the **=DataSets!DataSet1.CommandText** where DataSet1 is the name of the data set where the query lives. We can make the text hidden by default but visible by toggling some control (see Database Configuration and Properties report for an example)

**Comment by PiJoCoder** [comment]
@hacitandogan, would you like to think about this one next. The request here is to expose the actual query behind the report in case people want to use it for direct analysis in SSMS. I can demo if you'd like

**Comment by hacitandogan** [comment]
@PiJoCoder , sure I will check this one and ping you for the demo and sync.

**Comment by PiJoCoder** [comment]
> @PiJoCoder , sure I will check this one and ping you for the demo and sync.

You can use logic similar to this (in server configuration report), where the text of the query is not exposed at first, but we can have some toggle +/- to show it

![image](https://github.com/microsoft/SqlNexus/assets/23519517/7504223d-8685-41e9-b8d0-d051e1edcef9)

**Comment by hacitandogan** [comment]
@PiJoCoder 

I did a sample on one of the reports to test this.

This is server configuration report , which has multiple datasets;

Hidden:
<img width="724" alt="image" src="https://github.com/microsoft/SqlNexus/assets/25321786/2ce372ba-d7d9-48a0-853b-a80c0701f673">

Visible:
<img width="734" alt="image" src="https://github.com/microsoft/SqlNexus/assets/25321786/2ad70c7b-fe26-4e68-9c05-7fa885ab853b">

Tried to keep it plain and simple but should we highlight that more or is this good ?
Once we clarify how it should look , my plan is to use same approach on the other reports as well.

**Comment by PiJoCoder** [comment]
> @PiJoCoder
> 
> I did a sample on one of the reports to test this.
> 
> This is server configuration report , which has multiple datasets;
> 
> Hidden: <img alt="image" width="724" src="https://user-images.githubusercontent.com/25321786/271009334-2ce372ba-d7d9-48a0-853b-a80c0701f673.png">
> 
> Visible: <img alt="image" width="734" src="https://user-images.githubusercontent.com/25321786/271010851-2ad70c7b-fe26-4e68-9c05-7fa885ab853b.png">
> 
> Tried to keep it plain and simple but should we highlight that more or is this good ? Once we clarify how it should look , my plan is to use same approach on the other reports as well.

I agree with you that plain and simple is good. I don't think we need to go fancy on this. One thing that I image is to add this at the bottom of reports, away from other report data so people don't get confused.  Is that how you image it too?

**Comment by hacitandogan** [comment]
@PiJoCoder , I sent a PR for one report only so you can also see and test this. If we are OK with this , I can implement the same for all reports.

**Comment by PiJoCoder** [comment]
> @PiJoCoder , I sent a PR for one report only so you can also see and test this. If we are OK with this , I can implement the same for all reports.

Thank you! I'll test and let you know

**Comment by PiJoCoder** [comment]
> @PiJoCoder , I sent a PR for one report only so you can also see and test this. If we are OK with this , I can implement the same for all reports.

Looks great, @hacitandogan! Let's proceed with it. Thank you

**Comment by hacitandogan** [comment]
PR merged , closing this item.
