### ISSUE TITLE
Generate Best Practice/Analysis Summary warning for Common Criteria Compliance.

### ISSUE THREAD

**Issue by troymoen1** [microsoft/SqlNexus#243]
In a recent SharePoint support case, a user that had recently upgraded SQL and SharePoint was seeing performance issues. It was eventually found that Common Criteria Compliance was the root cause. A warning in Nexus that this is enabled and can and will cause performance issues would be great. Note that we do call out performance issues in the public article:

https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/common-criteria-compliance-enabled-server-configuration-option?view=sql-server-ver16

**Comment by PiJoCoder** [comment]
@troymoen1 this is now added. Thanks for filing
