### ISSUE TITLE
Workingset Trimming Report not working

### ISSUE THREAD

**Issue by asavioliMSFT** [microsoft/SqlNexus#247]
Every time we try to open this report on Nexus, following errors are occurring:

![image](https://github.com/microsoft/SqlNexus/assets/49494532/8a42af01-c062-460d-bf68-6aad80789afc)

![image](https://github.com/microsoft/SqlNexus/assets/49494532/0be73bf7-e668-45f4-b981-a510f143322e)

**Comment by hacitandogan** [comment]
Field name  "Indicators" does not exists , removing this from DataSet_MemClerks fixing this error as the field is not used in the report.

@PiJoCoder , @asavioliMSFT 
Correct fields are   ,[IndicatorsProcess]      ,[IndicatorsSystem]      ,[IndicatorsPool]  , should we add those to the grid ?

<img width="832" alt="image" src="https://github.com/microsoft/SqlNexus/assets/25321786/7a41c1da-eebb-4053-9668-99264e45e945">

**Comment by asavioliMSFT** [comment]
Yes. These column are the most important ones, that will show where the memory pressure is

**Comment by PiJoCoder** [comment]
Sure, we can add them to the grid. Thanks @hacitandogan!

**Comment by PiJoCoder** [comment]
Fixed
