### ISSUE TITLE
dm_db_stats_properties did not pulled by the Nexus when import from logscout

### ISSUE THREAD

**Issue by AtiyehDaghlas** [microsoft/SqlNexus#249]
dm_db_stats_properties did not pulled by the Nexus when import from logscout or pssdiag
The file is already collected by the logscout
Nexus ver. 7.23.05.18

**Comment by PiJoCoder** [comment]
Hello @AtiyehDaghlas, the ability to import this rowset has been there since at least 2022 . See code here https://github.com/microsoft/SqlNexus/blob/7a86cbf3a1ea46de7c834a51d2fb74a63ac5d12e/RowsetImportEngine/TextRowsets.xml#L2022

1. Can you try the latest build just in case - https://github.com/microsoft/SqlNexus/releases/tag/7.23.06.06
2. Also, can you manually examine the raw data in the _PerfStatsSnapshotStartup.out file to see if there are some issues with it to prevent import. There must be an identifier tag -- sys.dm_db_stats_properties -- immediately followed by (no empty lines) the result set. Here is a sample output of what mine looks like from a successful import I just made.

```
-- sys.dm_db_stats_properties --
Database_Id Database_Name                                                                                                                    Schema_Name                                                                                                                      Object_Name                                                                                                                      object_id   stats_id    Statistics_Name                                                                                                                  last_updated                           rows                 rows_sampled         steps       unfiltered_rows      modification_counter persisted_sample_percent
----------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ----------- ----------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------- -------------------- -------------------- ----------- -------------------- -------------------- ------------------------
          6 AdventureWorks2016                                                                                                               Sales                                                                                                                            SalesTaxRate                                                                                                                        14623095           1 PK_SalesTaxRate_SalesTaxRateID                                                                                                              2017-10-19 17:24:46.5000000                   29                   29          16                   29                    0                      0.0
          6 AdventureWorks2016                                                                                                               Sales                                                                                                                            SalesTaxRate                                                                                                                        14623095           2 AK_SalesTaxRate_StateProvinceID_TaxType                                                                                                     2017-10-19 17:24:48.0366667                   29                   29          22                   29                    0                      0.0
          6 AdventureWorks2016                                                                                                               Sales                                                                                                                            SalesTaxRate                                                                                                                        14623095           3 AK_SalesTaxRate_rowguid                                                                                                                     2017-10-19 17:24:48.0366667                   29                   29          28                   29                    0                      0.0
       
```

**Comment by AtiyehDaghlas** [comment]
Thanks for reply Joseph Pilov,

I have several cases, most of them working fine without any errors, but I have two issues with different customer and different LogScout collection:


  1.  We have data inside file _PerfStatsSnapshotStartup.out under sys.dm_db_stats_properties , but the table does not imported by Nexus database

--sys.dm_db_stats_properties--
Database_Id Database_Name                                                                                                                    Object_Name                                                                                                                      object_id   stats_id    last_updated                           rows                 rows_sampled         steps       unfiltered_rows      modification_counter persisted_sample_percent
----------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ----------- ----------- -------------------------------------- -------------------- -------------------- ----------- -------------------- -------------------- ------------------------
          6 CODEMANAGEMENT                                                                                                                   Code


  1.  Error when collecting logs from LogScout "tbl_dm_db_stats_properties"

Msg 207, Level 16, State 1, Server PRODDBV24, Line 17
Invalid column name 'database_name'.


-- sys.dm_db_stats_properties --

**I think in this case No.2, We need to open ticket with LogScout team, please let me know if I am correct**

Please let me know if you need any more information

Best Regards,
Atiyeh Daghlas
SUPPORT ENGINEER
SQL SERVER Support Engineer
Office: +962 (6) 556 4103
***@***.******@***.***>
Sat - Wed 9 AM - 6 PM UTC +3

If you have any feedback about my work, please let either me or my manager Georgiana-Mihaela Ghidanac know at ***@***.******@***.***>

Need help outside of my working hours? Please use the Premium Support Numbers found here<https://hubstaticsite.z5.web.core.windows.net/>

**Comment by PiJoCoder** [comment]
@AtiyehDaghlas, did you get your questions on this answered? I am closing for now. If you need to continue discusison, please reopen.

**Comment by PiJoCoder** [comment]
I understand downloading the latest version of SQL LogScout took care of the issue
