### ISSUE TITLE
Tempdb Space usage report shows incorrect data when large result sets are returned

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/SqlNexus#310]
Report seems to show incorrect results:

![image](https://github.com/microsoft/SqlNexus/assets/23519517/43fa83ff-1b51-4460-b541-83f450a01d92)

The T-SQL query returns different results (correct)

![image](https://github.com/microsoft/SqlNexus/assets/23519517/fcc562f0-24fe-4428-96af-4a59f4448d9e)

Possibly happening due to a very large result set from 

```sql
SELECT ssu.runtime,
       ssu.session_id,
       tsu.exec_context_id,
       tsu.cpu_time,
       CONVERT(DECIMAL(10, 3), ssu.internal_objects_alloc_page_count / 128.0) AS internal_objects_alloc_MB,
       CONVERT(DECIMAL(10, 3), ssu.internal_objects_dealloc_page_count / 128.0) AS internal_objects_dealloc_MB,
       CONVERT(DECIMAL(10, 3), ssu.user_objects_alloc_page_count / 128.0) AS user_objects_alloc_MB,
       CONVERT(DECIMAL(10, 3), ssu.user_objects_dealloc_page_count / 128.0) AS user_objects_dealloc_MB,
       CONVERT(DECIMAL(10, 3), ssu.user_objects_deferred_dealloc_page_count / 128.0) AS user_objects_deferred_dealloc_MB,
       ssu.open_transaction_count,
       ssu.program_name,
       ssu.most_recent_query,
       tsu.batch_text,
       tsu.statement_text,
       tsu.wait_type,
       tsu.wait_time
FROM dbo.tbl_dm_db_session_space_usage AS ssu
    LEFT OUTER JOIN dbo.tbl_dm_db_task_space_usage AS tsu
        ON ssu.session_id = tsu.session_id
WHERE (ssu.internal_objects_alloc_page_count >= 1280)
      OR (ssu.user_objects_alloc_page_count >= 1280)
```

**Comment by hacitandogan** [comment]
Problem is the mapping for the field in the report, this supposed to show “internal objects dealloc (MB)”  but mapped field is “[user_objects_dealloc_MB]”  which is actually 0 for the sample line;

![image](https://github.com/microsoft/SqlNexus/assets/25321786/380b37c7-4da8-4669-9b8e-1c1f6ec58680)
 
<img width="909" alt="image" src="https://github.com/microsoft/SqlNexus/assets/25321786/ae3b45fe-d8c1-479a-aa15-8e252dbc9f8f">

![image](https://github.com/microsoft/SqlNexus/assets/25321786/41099352-1b6e-457b-be12-da1606a8e0ce)

I changed this now.
