### ISSUE TITLE
Loaded_modules report is empty - need to update report query 

### ISSUE THREAD

**Issue by asavioliMSFT** [microsoft/SqlNexus#313]
In the latest version of Log Scout, the loaded modules have been moved to the MiscDiagInfo file. Because of that, the report on nexus will always return nothing. We must change the query accordingly to fix this.

Fix is simple. We just must to change the WHERE clause of the report on Nexus, since now the input file name has MiscDiagInfo and current filter " WHERE input_file_name LIKE '%Shutdown.out'" will no longer work.

![image](https://github.com/microsoft/SqlNexus/assets/49494532/9f76232f-8d5f-4f19-a6bf-d656ff5e2413)

**Comment by PiJoCoder** [comment]
@asavioliMSFT, we likely just need to remove the WHERE clause as this rowset is no longer collected 2 times on startup and shutdown. We could even modify the XML rowset and remove the "input_file_name" column as it was used to filter out startup vs. shutdown stuff. https://github.com/microsoft/SqlNexus/blob/31851147986212cb2e62d8edeaf0ee34773ffdb5/RowsetImportEngine/TextRowsets.xml#L228
