### ISSUE TITLE
SQLNexus crashes on WIndows 10

### ISSUE THREAD

**Issue by Imprecator** [microsoft/SqlNexus#318]
SQL Nexus crashes with a .Net runtime error on WIndows 10. Using .Net 4.8 patched with KB5034468 

![image](https://github.com/microsoft/SqlNexus/assets/20953879/85474bde-1026-41d0-aee7-24fe45d7ec42)
![image](https://github.com/microsoft/SqlNexus/assets/20953879/c4dbb784-e2c7-4123-9a68-350ca17cdf0e)

**Comment by PiJoCoder** [comment]
@Imprecator can you provide info from the Detalles tab - possibly a call stack?
Also, which version of SQL Nexus are you using?
Finally, how can we reproduce this issue? Do you have some repro steps

**Comment by PiJoCoder** [comment]
Closing. Please reopen if you have a way for us to reproduce
