### ISSUE TITLE
SQL Nexus 6.0 references ReportViewer 13 issue

### ISSUE THREAD

**Issue by sm8680** [Microsoft/SqlNexus#33]
SQL Nexus 6 when you run the application.  One gets the following error Could not load file or assembly 'Microsoft.ReportViewer.Common, Version=13.0.0.0,'  

![error](https://user-images.githubusercontent.com/25964294/28777419-fd2fc87e-75c8-11e7-96c9-3fb1bb0ef8c6.jpg)

Online I was able to find ReportViewer 11 and ReportViewer 12.  Do you know how I can get my hands on a reportviewer.msi for version 13?  If I uninstall previous versions of ReportViewer and then run SQL Nexus 5.5 I get the same error except different Version which if I recall was 11.  Now when I reinstalled that version I had no issue.  I looked on CodePlex and Github looking to see if there are references to 
a new version of reportviewer to no avail.

**Comment by iantonio** [comment]
To solve I downloaded this:

https://www.nuget.org/api/v2/package/Microsoft.ReportingServices.ReportViewerControl.WebForms.Preview/130.1700.305

After changed the type to .zip and extracted is to a folder. Copied all the content from lib folder to the Nexus folder, now it's starting successfully.

**Comment by sm8680** [comment]
Thanks that did work.

**Comment by iantonio** [comment]
For solve this problem in a correct way, you must:

i.	Download and install enu\x86\sqlsysclrtypes.msi
ii.	Download and install enu\x86\reportviewer.msi

From:

https://www.microsoft.com/en-us/download/details.aspx?id=52676

The links from installation page is going to SQL 2012 components and you must have SQL 2016 components.

**Comment by louis-li** [comment]
Fixed the link, thanks iantonio for the new link.
