### ISSUE TITLE
Replication Report Not Showing on Main Report Listing when tbl_repl_msmerge_subscriptions table is empty - Remove Unneeded Dependency

### ISSUE THREAD

**Issue by JamesFerebee** [microsoft/SqlNexus#364]
Query to determine whether replication report displays on the main listing checks to see if any rows exist in tbl_repl_msmerge_subscriptions. The report itself doesn't have a dependency on this table and the records are likely to be blank. Remove this query from the main report listing.

**Comment by PiJoCoder** [comment]
@JamesFerebee can you open a separate branch for this issue from master and fix it there as this is not an accessibility change and also we may have to do remove the AccessibilityEnhancements branch.

**Comment by JamesFerebee** [comment]
from sql perf main.rdl, remove: 
"
INSERT INTO @tbl_reports
(
    ReportName,
    ReportDisplayName,
    ReportDescription,
    VersionApplied,
    Category,
    ValidationObject,
    SeqNo,
    DataCollection,
    Manditory,
    CategorySeq
)
VALUES
('Replication_Topology_C', 'Replication Topology', 'Replication Topology in hierarchycal order', 1 | 2 | 4 | 8,
 'Replication', 'dbo.tbl_repl_msmerge_subscriptions', 200, 'Replication', 1, 2000);
"

**Comment by PiJoCoder** [comment]
Resolved by PR #370
