### ISSUE TITLE
Unhandled exception while running sqlnexus.exe (jackli)

### ISSUE THREAD

**Issue by uniqalex** [Microsoft/SqlNexus#40]
Tested on:
Windows 10
Windows Server 2012 R2

Installed 
SQLSysClrTypes.msi
ReportViewer.msi
RMLSetup_AMD64.msi

After running sqlnexus.exe I see this exception:
![image](https://user-images.githubusercontent.com/22915408/29659599-7c7a1c04-88c7-11e7-8c94-e340a746393c.png)

**Comment by uniqalex** [comment]
The problem is that on the page https://github.com/Microsoft/SqlNexus/wiki/Installation there are links for componetns (CLR Types, Report Viewer, RML Utilities) throws on 2012/2014 versions. 
But SqlNexus.6.0.0.8 is needed SQL SERVER 2016 assemplies (ReportView and SQLSysClrTypes)
This components must be installed from https://www.microsoft.com/en-us/download/details.aspx?id=52676
After installing this componetns from new link - my problem was fixed.

**Comment by vikasrana2006** [comment]
Fixed issue after installing SQL SERVER 2016 assemplies (ReportView and SQLSysClrTypes)
