### ISSUE TITLE
Timestamp issues when importing PSSDIAG using SQL Nexus [Masha]

### ISSUE THREAD

**Issue by suresh-kandoth** [microsoft/SqlNexus#41]
As you know, xEvents convert event time field to local time zone of computer that is importing the data. so when we import both PerfStats and xEvents captured from pssdiag, our timestamps don’t match, which makes it pretty difficult to troubleshoot correlative data. Is there any way we can like… force SQL Nexus to change the time zone of the readtrace data to whatever timezone the perfstats file is in (from the customer server timezone)?

**Comment by PiJoCoder** [comment]
This is a PSSDIAG issue, but yes definitely an issue. I attempted a fix of this a few years ago. It should be possible.

**Comment by PiJoCoder** [comment]
Fixed with 
- PSSDIAG commit https://github.com/microsoft/DiagManager/commit/2d38ce5036a4dd829cc8643a9a4744594e2ac81a#diff-8bc0322fd2ed1906ca8ae48de4c21506bc7f5f24f962e9fa6d9301bec99a68e5
- commit e69ebebaf14ee22560e1471d990ecde6dba4e4e1
