### ISSUE TITLE
Nexus is incorrectly saying there is no blocking occurring when there’s clearly blocking [Masha]

### ISSUE THREAD

**Issue by suresh-kandoth** [microsoft/SqlNexus#44]
See email from Masha on 2017-10-12

**Comment by gambit9009** [comment]
This may be fixed in multiple fixes where we found the importer might not import rows.  One of the biggest row droppers was if the tsql snip had comments in it like '--'.  SQL Nexus would think of those as headers and then not get any rows after those until the next header started

**Comment by PiJoCoder** [comment]
We have fixed multiple issues where rowsets were not importing. This is likely fixed by now. Please reopen if you have a repro to share.
