### ISSUE TITLE
Data Collector

### ISSUE THREAD

**Issue by goforebroke** [microsoft/SqlNexus#47]
The tools has changed a little bit so bear with me...

I downloaded from the main page and navigated to the "data collectors" folder

I updated the "StartSQLDiagDetailed_Trace2014.cmd" file to find the path of the sqldiag.exe location on the server.

I ran the command StartSQLDiagDetailed_Trace2014.cmd from a cmd window and got the following error...

2017/10/19 08:47:55.12 SQLDIAG Configuration file H:\SqlNexus-master\SqlNexus-ma
ster\DataCollectors\Diag2014\sqldiag_detailed.xml does not exist

In the old days, you downloaded the Perf scipts, update your batch file to the sqldiag location, and updated the xml file to specify a sql instance if needed.

What am I missing? All the old sql perf files and the xml files are absent from the "data collectors" folder

Thx

**Comment by goforebroke** [comment]
A little more research and reading.... all the of the data is now collected through the DiagMgr utility.

**Comment by PiJoCoder** [comment]
Thanks for report. Looks like you found the answers you need. But for reference of others - [wiki/How-to-use-SQL-Nexus](https://github.com/microsoft/SqlNexus/wiki/How-to-use-SQL-Nexus)
