### ISSUE TITLE
RML Utilities for SQL2016 and SQL2017

### ISSUE THREAD

**Issue by ghost** [microsoft/SqlNexus#49]
Hi,

currently there is no public RML utilities available for SQL Server 2016 and newer (I can use SQLNexus only for SQL Server version 2014 or older). Can you public a new version of them where we can use also profiler/xperf traces for SQL Server 2016 or later?

Thanks,
Octavian

**Comment by suresh-kandoth** [comment]
Octavian, we have a preview build that can process 2016 and 2017 versions. If you want to try it out, please send me an email : suresh_dot_kandoth_at_microsoft_dot_com
We have plans to update the public downloads with the latest versions.
Thanks
Suresh

**Comment by DanielAdeniji** [comment]
Suresh Kandoth or anyone else that is able to, please provide a link for RML utilities - v2016/v2017.

Daniel Adeniji

**Comment by johnmart82** [comment]
Is there any update on when RML that supports 2016/2017 will be available publicly?

**Comment by fatherjack** [comment]
Is there news on support for SQL 2016/2017+2019 please?

**Comment by suresh-kandoth** [comment]
Please see instructions from https://github.com/microsoft/SqlNexus/wiki/RML-Utility to get the latest updates to ReadTrace that can process all versions of SQL Server.

**Comment by fatherjack** [comment]
Has this been closed with no fix? Will we always have to download DEA and get the working ReadTrace from there? This is very disappointing.
