### ISSUE TITLE
SQL authentication not used for readtrace

### ISSUE THREAD

**Issue by seansensus** [microsoft/SqlNexus#50]
Tried using SqlNexus to import files from pssdiag, but it fails login with sql authentication. Looks like it's defaulting to windows authentication. All other files look like they were imported. Only the *pssdiag*.xel files failed.

![image](https://user-images.githubusercontent.com/7735214/31948986-70120fb4-b895-11e7-9f4d-ebc2a5500d25.png)

**Comment by seansensus** [comment]
Found this in the code:
ReadTraceNexusImporter.cs  line 409
(this.useWindowsAuth ? "-E" : String.Format("-U\"%s\" -P\"%s\"", this.sqlLogin, this.sqlPassword))

I believe the %s should be {0} and {1}

Also in FileImporter.cs hard coded connection strings
line 25: string ConnString = string.Format("Data Source={0}; Initial Catalog={1};Integrated Security=SSPI", m_ServerName, m_DatabaseName);

line 65: SqlConnection conn = new SqlConnection(string.Format("Data Source={0}; Initial Catalog={1}; Integrated Security=SSPI", m_ServerName, m_DatabaseName));

**Comment by ram2ybabu** [comment]
This issue is fixed in the latest nexus release 6.21.1.21
