### ISSUE TITLE
ERROR: Attempt to initialize trace file reader failed with operating system error 0x80004005

### ISSUE THREAD

**Issue by khalednsair** [microsoft/SqlNexus#54]
Hi this file has full authority for everyone. can you help us identifying this issue 

INFO: Starting build of XEL sequence order index
11/08/17 10:37:25.361 [0X000012C0]     XEL INDEXING PROGRESS: 1480 events found and 0 events skipped in c:\temp\pssd\output\IPLC-KNSA-W__pssdiag_xevent_0_131546359772530000.XEL
11/08/17 10:37:25.363 [0X00002EA0]  INFO: Total events indexed: 1480 (Rate: 56000/sec)
11/08/17 10:37:25.366 [0X00002EA0]  INFO: Event range 1 to 1480 for IPLC-KNSA-W__pssdiag_xevent_0_131546359772530000
11/08/17 10:37:25.371 [0X00002EA0] XEL READER ERROR: The tookLock argument must be set to false before calling this method.
11/08/17 10:37:25.371 [0X00002EA0] XEL READER ERROR: Attempt to open file c:\temp\pssd\output\IPLC-KNSA-W__pssdiag_xevent_0_131546359772530000.XEL failed, see previous error(s) for more details.
11/08/17 10:37:25.371 [0X00002EA0] ERROR: Attempt to open c:\temp\pssd\output\IPLC-KNSA-W__pssdiag_xevent_0_131546359772530000.XEL failed.
11/08/17 10:37:25.371 [0X00002EA0] *** ERROR: Attempt to initialize trace file reader failed with operating system error 0x80004005 (Unspecified error)
11/08/17 10:37:25.375 [0X00002EA0] Reads completed - Global Error Status 0xfffffffe

**Comment by suresh-kandoth** [comment]
Please send me an email suresh_dot_kandoth_at_microsoft_dot_com for a newer/latest build of ReadTrace fro you to try and see if it resolves this problem.

**Comment by javdvd** [comment]
> Please send me an email suresh_dot_kandoth_at_microsoft_dot_com for a newer/latest build of ReadTrace fro you to try and see if it resolves this problem.

Hi Suresh, do you know if this issue is resolved? If not, do you have any work around or when this might be resolved? Thanks 👍

**Comment by suresh-kandoth** [comment]
Please use the latest utilities from https://github.com/microsoft/SqlNexus/wiki/RML-Utility
