### ISSUE TITLE
Missing table in SqlNexus database tbl_PERF_STATS_SCRIPT_RUNTIMES

### ISSUE THREAD

**Issue by seansensus** [microsoft/SqlNexus#55]
I locally fixed the database connection strings in my previous reported issue and ran into this:

![image](https://user-images.githubusercontent.com/7735214/32625757-5dd94530-c54a-11e7-98e1-ae7653b51ed9.png)

**Comment by nnerson** [comment]
Hello,

I faced a similar Issue. The problem was related to Collation. If the model database is not CI then you may need to manually create the database using those commands:

Use [master]
Go
Drop Database [sqlnexus]
Go
Create Database [sqlnexus]
Go
Alter Database [sqlnexus] Collate Latin1_General_CI_AI
Go

In this case, don't drop the current DB before importing.

I hope it is useful
Nicolas.

**Comment by mrittberg** [comment]
Hello,

I am also facing this problem, unfortunately, the workaround (new creation of the table) didn't work.

I am grateful for any help.

**Comment by seansensus** [comment]
Hi,

I didn’t spend any time trying to figure this out, and moved on to using these tools:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit

Enjoy!

Sean

**Comment by gambit9009** [comment]
Double sided issue here.  
#1.  Check the table to make sure it exists before blindly doing a.  
fmImport.cs line 1128
https://github.com/microsoft/SqlNexus/blob/16016cbd87d7c9647ee173c0d48534c335f90875/sqlnexus/fmImport.cs#L1128
` cmd.CommandText = "select count (distinct runtime) 'NumberOfRuntimes' from tbl_PERF_STATS_SCRIPT_RUNTIMES";`

#2. Why was the table not there?  Looking in code can see how it is possible.  We create that table from tbl_OS_WAIT_STATS without checking to see if that data is blank.

```
IF OBJECT_ID ('tbl_PERF_STATS_SCRIPT_RUNTIMES') IS NOT NULL DROP TABLE tbl_PERF_STATS_SCRIPT_RUNTIMES
GO
--it used to use tbl_requests. but that table wont' get much data if server is idel. wait stats is gauranteed to generate
SELECT DISTINCT runtime INTO tbl_PERF_STATS_SCRIPT_RUNTIMES FROM tbl_OS_WAIT_STATS ORDER BY runtime
GO
```

Worst case.  Create blank table. Insert into it.
