### ISSUE TITLE
SQL 2014. RML ( ReadTrace) utility error in parsing of .TRC and .XEL files

### ISSUE THREAD

**Issue by rud0x7b6** [Microsoft/SqlNexus#57]
Hello,

I use SQLNexus and when I import data from SQLDiag I always have an error "Import failed" (see attach
[trc.log](https://github.com/Microsoft/SqlNexus/files/1505232/trc.log)
[xel.log](https://github.com/Microsoft/SqlNexus/files/1505233/xel.log)
![error_pict](https://user-images.githubusercontent.com/10798119/33259325-9254f878-d36d-11e7-9753-68c49c596f15.png)
).

This error is related to .TRC or .XEL files parsing. ReadTrace can parse several files and get crash on 10th, for example, file.

Virtual Machine where I collect logs: Windows Server 2012R2 Standard and SQL Server 2014 standard. All updates installed.

I have tried:

- Start SQLNexus in Windows 10, Windows 7 and Windows Server 2012 R2.

- Use RML Utilities x86 and x64 ( RML Utilities for SQL Server (x64) CU4  https://www.microsoft.com/en-us/download/details.aspx?id=4511 )

In the logs I see source file where the error occurred, line of code, but I couldn't find sources of RML.

**Comment by suresh-kandoth** [comment]
Please send me an email : suresh_dot_kandoth_at_microsoft_dot_com
I will give you an updated/latest version of ReadTrace for you to try and we can check if that fixes your problem.
Thanks
Suresh

**Comment by rud0x7b6** [comment]
Thank you Suresh, I've sent an email to you.

**Comment by rud0x7b6** [comment]
Issue has been closed.

**Comment by HolisticDeveloper** [comment]
What was the resolution? How do we get the newer version of ReadTrace?

**Comment by rud0x7b6** [comment]
I've checked download center and there is old version there. I think you should email to suresh_dot_kandoth_at_microsoft_dot_com ,  see above.

**Comment by HolisticDeveloper** [comment]
Suresh provided a private download and this resolved my issue. It would be nice if this could be made publicly available.

**Comment by rud0x7b6** [comment]
>  It would be nice if this could be made publicly available.

They promised.

**Comment by ghbjingli** [comment]
I have the same issue. Just tried with the latest version from here: https://www.microsoft.com/en-us/download/details.aspx?id=4511. No help. Just send an email to Suresh.
