### ISSUE TITLE
SSB Custom Script fails to properly get the Group By results for Transmission Queue

### ISSUE THREAD

**Issue by ghost** [microsoft/SqlNexus#62]
Found this during a case. I will fix this and upload the new SSB script.

**Comment by PiJoCoder** [comment]
Wrong repo? Was this meant for Diagmanager/Pssdiag?

**Comment by gambit9009** [comment]
maybe not what was meant, but I do see in DiagManager this might have been fixed...
`SELECT COUNT(*) as TQ_GroupCnt, transmission_status FROM sys.transmission_queue GROUP BY transmission_status`
