### ISSUE TITLE
 XEL READER ERROR: The tookLock argument must be set to false before calling this method.

### ISSUE THREAD

**Issue by stevensnicole** [microsoft/SqlNexus#64]
Using SQLNexus on a new laptop and the ReadTrace Report will not open.

Traced it back to the following command failing

readtrace.exe -S"HOSTNAME\SQL2K17DEV" "-dsqlnexus" -E -T18 -T28 -T29 "-IC:\dump\pssdiag\output\SERVERNAME__pssdiag_xevent_0_131616939684720000.xel" -f   "-oC:\Users\username\AppData\Local\Temp\RML" -H"!PSSDIAG"

It fails with the trace below, running on Windows 10, SQL 2017, PSSDiag run against Windows Server 2016 Std, SQL Server 2017.3

Many thanks,

icklecoder

01/30/18 10:15:35.520 [0X00002E18] XEL READER ERROR: The tookLock argument must be set to false before calling this method.
01/30/18 10:15:35.520 [0X00002E18] XEL READER ERROR: Attempt to open file C:\dump\pssdiag\output\SERVERNAME__pssdiag_xevent_0_131616939684720000.XEL failed, see previous error(s) for more details.
01/30/18 10:15:35.521 [0X00002E18] ERROR: Attempt to open C:\dump\pssdiag\output\SERVERNAME__pssdiag_xevent_0_131616939684720000.XEL failed.
01/30/18 10:15:35.522 [0X00002E18] ERROR: Unable to construct proper base metadata generation for C:\dump\pssdiag\output\SERVERNAME__pssdiag_xevent_0_131616939684720000.XEL
01/30/18 10:15:35.522 [0X00002E18] ERROR: Attempt to determine list of .XEL files failed.
01/30/18 10:15:35.523 [0X00002E18] *** ERROR: Attempt to initialize trace file reader failed with operating system error 0x80070006 (The handle is invalid)
01/30/18 10:15:35.528 [0X00002E18] Reads completed - Global Error Status 0xfffffffe
01/30/18 10:15:35.528 [0X00002E18] Signaling worker threads to complete final actions.
01/30/18 10:15:35.528 [0X00002E18] Waiting for the worker threads to complete final actions.
01/30/18 10:15:35.529 [0X00002E18] Performing general cleanup actions.
01/30/18 10:15:35.529 [0X00002E18] Total Events Processed: 0
01/30/18 10:15:35.529 [0X00002E18]  Total Events Filtered: 0
01/30/18 10:15:35.530 [0X00002E18] ==============================================
01/30/18 10:15:35.530 [0X00002E18] WARNING: A significant portion of the events where filtered.
01/30/18 10:15:35.530 [0X00002E18]          You may want to check the filtering criteria.
01/30/18 10:15:35.530 [0X00002E18] ==============================================
01/30/18 10:15:35.531 [0X00002E18] *******************************************************************************
* ReadTrace encountered one or more ERRORS. An error condition typically      *
* stops processing early and the ReadTrace output may be unusable.            *
* Review the log file for details.                                            *
*******************************************************************************
01/30/18 10:15:35.531 [0X00002E18] ***** ReadTrace exit code: -2
01/30/18 10:15:35.532 [0X00002E18]  INFO: Max set-aside XEL event hash table entry count: 0

**Comment by diegocaracciolo** [comment]
Did you find a solution for this problem?

**Comment by icklecoder** [comment]
Nope it just doesn't work, known issue.

**Comment by javdvd** [comment]
Does anyone know how to resolve this issue? Thanks

**Comment by javdvd** [comment]
Ok. Thanks for the update. Hopefully we will get an update soon. Thanks again

**Comment by amaldonadoortec** [comment]
I got the same error
I collected the event data using the template provided by RML and it generated XEL files, however read trace got me the same error I collected data on SQL 2014 however I used a SQL 2012 to try to store the results, but it does not matter the process did then get until there

03/08/19 16:15:08.424 [0X00001690] Using SQLOLEDB version 11.0.6518.0
03/08/19 16:15:08.426 [0X00001690] Connected to SQL Server Version, Major: 11, Minor: 0, Build: 6020
03/08/19 16:15:08.427 [0X00001690] Creating or clearing the performance database
03/08/19 16:15:09.100 [0X00001690] Detecting list of matching XEL files in the same directory
03/08/19 16:15:09.127 [0X00001690]  INFO: Using additional file system cache read ahead for XEL input
03/08/19 16:15:09.133 [0X00001690] XEL READER ERROR: The tookLock argument must be set to false before calling this method.
03/08/19 16:15:09.134 [0X00001690] XEL READER ERROR: Attempt to open file C:\Temp\Volume_Test_QA_0_131965490086500000.XEL failed, see previous error(s) for more details.
03/08/19 16:15:09.136 [0X00001690] ERROR: Attempt to open C:\Temp\Volume_Test_QA_0_131965490086500000.XEL failed.
03/08/19 16:15:09.138 [0X00001690] ERROR: Unable to construct proper base metadata generation for C:\Temp\Volume_Test_QA_0_131965490086500000.XEL
03/08/19 16:15:09.139 [0X00001690] ERROR: Attempt to determine list of .XEL files failed.
03/08/19 16:15:09.141 [0X00001690] *** ERROR: Attempt to initialize trace file reader failed with operating system error 0x80070006 (The handle is invalid)
03/08/19 16:15:09.147 [0X00001690] Reads completed - Global Error Status 0xfffffffe
03/08/19 16:15:09.148 [0X00001690] Signaling worker threads to complete final actions.
03/08/19 16:15:09.149 [0X00001690] Waiting for the worker threads to complete final actions.
03/08/19 16:15:09.150 [0X00001690] Performing general cleanup actions.
03/08/19 16:15:09.152 [0X00001690] Total Events Processed: 0

**Comment by Onninen** [comment]
I got the same error. I found this workaround, getting newer versions of ReadTrace and other binaries. It worked fine for me from: https://stackoverflow.com/questions/41952391/sql-server-2016-readtrace-rml-tool.

**Comment by suresh-kandoth** [comment]
Please use the latest versions of ReadTrace as discussed in https://github.com/microsoft/SqlNexus/wiki/RML-Utility
