### ISSUE TITLE
Request: Grab filter driver information in PSSDiag and import in SQL Nexus

### ISSUE THREAD

**Issue by MashaMSFT** [microsoft/SqlNexus#65]
Filter drivers so frequently cause performance issues with SQL, and yet for us to identify them during a performance case, we'll either have to grab that manually, or run an SDP package alongside the PSSDiag. To help minimize how much data we ask the customer collect, it may behoove us to grab filter driver information during the PSSDiag. 

Thanks!

**Comment by PiJoCoder** [comment]
This is more of a PSSDIAG request. SQL LogScout currently collect fltmc outputs and we should make SQL Nexus import them. So we will re-purpose this item to implement the importing piece in Nexus.
