### ISSUE TITLE
how can i install the sqlnexus mainprogram？

### ISSUE THREAD

**Issue by 417989930** [microsoft/SqlNexus#69]
I download the sqlnexus packages from the main page，but how can i compile and install the main program？It's looks like had some files but it have not including sqlnexus.exe program?

**Comment by ram2ybabu** [comment]
Main page has information about installation steps. The release page has the .zip file with Nexus binaries. You have to unzip the binaries and find the sqlnexus.exe to launch the SQL nexus. Please make sure all the prerequisites which are installed mentioned installation section.
