### ISSUE TITLE
FileNotFoundException was unhandled during initial installation

### ISSUE THREAD

**Issue by ArtSotelo** [microsoft/SqlNexus#70]
I've attached a screen shot of the error.  The following was derived from VS2015 upon error;

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Microsoft.ReportViewer.WinForms.dll

Additional information: Could not load file or
[SQLnexusError.docx](https://github.com/Microsoft/SqlNexus/files/1903183/SQLnexusError.docx)
 assembly 'Microsoft.ReportViewer.Common, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.

**Comment by hillsrobin** [comment]
I have this very issue and with the ReportViewer 2015 run time installed.

**Comment by ferozbasha** [comment]
Any fixes for this issue?

**Comment by PiJoCoder** [comment]
Hello @artsotelo, @ferozbasha , and @hillsrobin  - thank you for reporting this issue. My suspicion is that the version of Report Viewer control is old. We had a [issue](https://github.com/microsoft/SqlNexus/issues/99) in that the documentation was pointing to an old Report Viewer download version. The correct version is 2016. You can download it here https://www.microsoft.com/en-us/download/details.aspx?id=56833 . See if this resolves it and let us know. We apologize for the troubles this issue caused to you all. And thank you for proactively reporting it.
