### ISSUE TITLE
Error In ReadTrace Importer When Importing Trace Files

### ISSUE THREAD

**Issue by danbo0001** [microsoft/SqlNexus#71]
Hi,

I have a feeling this is due to some version conflicts, but have gone as far as i can in troubleshooting and now need some help.

Steps to reach issue:-
Created a set of data collection config files using sqldiag config manager (latest version from github, v13.0.1600.32-public) that includes profiler traces.
Ran the data capture on a SQL Server 2016 instance.
Installed all versions of dependencies linked to from the current installation page links on this sqlnexus github site (https://github.com/Microsoft/SqlNexus/wiki/Installation) with the exception of sqlclrtypes for which i downloaded the sql server 2016 version instead of the 2014 one linked.
Ran sql nexus 6.0.0.8 and started an import of the captured files.
The import succeeded all the way up to the second last item - *.trc
Message was "(Importer:ReadTrace (SQL Profiler TRC files). Import failed. (2 sec, 0 rows inserted)"

Please let me know if i have missed off detailing any info e.g. versions etcand i will add to this post asap.

I saw a message on this board mentioning that the linked version of rmlutilities has a version of readtrace which is not compatible with sql 2016. i followed the instructions to get hold of the newer versions of the 4 required files via the Database Experimentation Assistant, but the subsequent import failed in exactly the same way :(

Can anyone help?

Thanks
Dan

**Comment by danbo0001** [comment]
I wonder if this is still supported....
It would be a shame if it isn't as it has helped me huge amounts over the years and I don't think there is anything else available that gives this kind of detail and analysis (feel free to shoot me down on this as long as you tell me what other stuff there is ;-)

Anyways, if anyone comes across this issue, I found the resolution - in desperation coz there was nothing else to try, I launched the sqlnexus exe as an administrator and the import of the trace files finally worked :)

**Comment by PiJoCoder** [comment]
Hello @danbo0001 . Thank you for reporting this. We apologize for such a long delay in responding to these issues. What you reported above is a RML Utilities issue, not strictly SQL Nexus. @suresh-kandoth  for awareness.
Yes, it appears that this is your core error "ERROR: Attempt to initialize trace file reader failed with operating system error **0x80070005 (Access is denied)**" - file access issue. Is it possible that the account you are logged in with in the console and with which RML (Readtrace.exe) is exacuted does not have access to the folder/drive where those files are located?
Also, I have seen Access Denied errors when Anti-virus locks files for scanning.
