### ISSUE TITLE
Nexus version for SQL Server 2012

### ISSUE THREAD

**Issue by SimonLiu74** [microsoft/SqlNexus#77]
It looks like the currently version 6.0.0.8 is only working for SQL server 2016. 

we are currently using SQL 2012, is it possible we have previous release available for downloading?

**Comment by ram2ybabu** [comment]
Nexus tool imports data into SQL Server database, so it should ideally work for any version for SQL Server (2012 and above). Open a new issue with error information if it raised any error with any specific version of SQL Server. 
I am closing the issue for now
