### ISSUE TITLE
Improve Trace / xEvent Warning for SQL performance impacts

### ISSUE THREAD

**Issue by glura** [microsoft/SqlNexus#78]
I'd like to see an improved or additional warning when potentially expensive traces and/or xEvents are found.  I've recently seen a couple of performance cases that likely would have been resolved much sooner if the Active Trace and xEvent report was inspected.
Currently, on the Best Practices & Analysis Summary report, we list an Excessive Trace Warning when multiple trace or xevents collections were detected.  BUT, to be honest, this warning is almost always there.  It's not uncommon for more than 1 light weight collection to exist or maybe multiple short collections.  When the warning is almost always there, people start to ignore it as it doesn't stand out and is often benign.
I'd like to see a "Potentially Expensive" trace warning displayed and be prominent.  Maybe even highlight the Active Trace & xEvent Report cell if the warning exists so people at least look at the report.  We have the event names that are collected and we know what events are more likely to impact performance than others (ex.  statement level events, execution plan events, etc), so we should be able to add some logic with an improved warning about potentially expensive traces.  This has potential to find causes or contributors of performance issues that can be easily missed.

**Comment by PiJoCoder** [comment]
Pssdiag and SQL LogScout already collect this data and have a column indicating whether an event is expensive or not. We just have to add these in the Best Practices summary report

**Comment by PiJoCoder** [comment]
Here is a screenshot of what the new rules look like

![image](https://user-images.githubusercontent.com/23519517/186552102-b844b968-1b0c-4731-a358-3b4b66233f4f.png)
