### ISSUE TITLE
Could not find stored procedure 'ReadTrace.spReporter_BatchAggScaleFactor'.

### ISSUE THREAD

**Issue by AlexAdministrator** [microsoft/SqlNexus#79]
Hello, 

During collecting data via Xevents by SQL nexus i receive error "Could not find stored procedure 'ReadTrace.spReporter_BatchAggScaleFactor'" , i can not open readtrace feature after importing to analyze collected queries over time , could you please help me with this issue ? I know that SQL nexus is good feature but without analyzing of collected query it is difficult to 
![image_2019_05_08T12_35_59_348Z](https://user-images.githubusercontent.com/50379613/57375913-57eae600-71a7-11e9-9e05-0af0cfd830a5.png)
analyze performance problem in specific time.

**Comment by PiJoCoder** [comment]
Hello @AlexAdministrator thank you for reporting this issue and we are so sorry for being slow in responding.
It appears from the screenshot you provided and the error that you have that the RML utilities were likely not installed on your system (PSSDIAG.XEL import failed). Please be sure to install the [RML Utilities (RMLSetup_AMD64.msi)](https://github.com/microsoft/SqlNexus/releases/download/09.04.0097/RMLSetup_AMD64.msi).

Please see the recently published [a build ](https://github.com/microsoft/SqlNexus/releases/tag/7.21.03.26)and the prerequisites to be installed. Also you can use the PS script to automate the installation of those prerequisites (one of which is RML utilities)
