### ISSUE TITLE
Importer:ReadTrace (SQL Profiler TRC Files)) Import failed

### ISSUE THREAD

**Issue by Susanthab** [microsoft/SqlNexus#82]
I'm using the latest version of SQLNexsus and SQL Profiler (trc) files import failed with the error below;

SQLNexus Information: 0 : (Importer:ReadTrace (SQL Profiler TRC Files)) Import failed. (1 sec, 0 rows inserted)

**Comment by suresh-kandoth** [comment]
Please use the latest utilities that process the TRC files. See https://github.com/microsoft/SqlNexus/wiki/RML-Utility

**Comment by namassivayabudidi** [comment]
still having issue. here is from readtrace log file
07/12/21 06:58:29.472 [0X00000E40]  INFO: Opened C:\Temp\dshsdboly2518c_pssd\output_07022021\output\DSHSDBOLY2518C__pssdiag_xevent_0_132696776056420000.XEL for input
07/12/21 06:58:29.473 [0X00000E40] Processing file: C:\Temp\dshsdboly2518c_pssd\output_07022021\output\DSHSDBOLY2518C__pssdiag_xevent_0_132696776056420000.XEL (XEL Converted)
07/12/21 06:58:30.678 [0X00000E40] Events Read: 6900000 Queued: 2 Processed/sec: 58771
07/12/21 06:58:31.001 [0X00000E40] Events Read: 6925000 Queued: 1 Processed/sec: 58823
07/12/21 06:58:31.343 [0X00000E40] Events Read: 6950000 Queued: 1 Processed/sec: 58864
07/12/21 06:58:31.678 [0X00000E40] Events Read: 6975000 Queued: 1 Processed/sec: 58908
07/12/21 06:58:32.029 [0X00000E40] Events Read: 7000000 Queued: 2 Processed/sec: 58945
07/12/21 06:58:32.119 [0X00002718] ERROR: Event runtime check:  Detected missing column [cached_text] in event [sp_cache_remove] at event sequence 7109288
07/12/21 06:58:32.120 [0X00002718] ERROR: Event sp_cache_remove
07/12/21 06:58:32.220 [0X00000E40] Events Read: 7025000 Queued: 1 Processed/sec: 59060
07/12/21 06:58:32.357 [0X00000E40] Events Read: 7050000 Queued: 186 Processed/sec: 59201
07/12/21 06:58:32.682 [0X00000E40] *** ERROR: Reader encountered operating system error 0x8007000D (The data is invalid) State: 0  Global Seq: 0
07/12/21 06:58:32.682 [0X00000E40] Reads completed - Global Error Status 0xffffffe7
07/12/21 06:58:32.683 [0X00000E40] Signaling worker threads to complete final actions.
07/12/21 06:58:32.687 [0X00000E40] Waiting for the worker threads to complete final actions.
07/12/21 06:58:32.716 [0X00000E40] Performing general cleanup actions.
