### ISSUE TITLE
Lack of updates, dead project

### ISSUE THREAD

**Issue by wapayne69** [microsoft/SqlNexus#85]
Seriously, this project is clearly dead. First of all the import does not support SQL auth anymore cos integrated authentication has been hardcoded coded somewhere. Then there is the initial setup that requires gathering bits and pieces elsewhere to make the tool run. 

This tool is a mess.

**Comment by PiJoCoder** [comment]
@wapayne69 , yes you are right. We are currently working on reviving it. Thank you for nudging us.
