### ISSUE TITLE
Remove "Idle" in Bottleneck Analysis in "Average System Idle CPU Utilization"

### ISSUE THREAD

**Issue by NathanMSFT** [microsoft/SqlNexus#88]
I was just looking at a Bottleneck Analysis report from a recent capture and saw this:

Average   System Idle CPU   Utilization: | 59%
-- | --
Average   SQL CPU Utilization: | 3%
Average   Resource Wait Time per Second: | 45996 ms  (46 active threads on average)

Actual CPU counters:
Counter Name                                             Avg                  Max                  Min Server          
--------------------------------------- -------------------- -------------------- -------------------- ----------------
Process(_Total)\% Processor Time                     397.534              401.112              320.248 \\{servername}\    
Process(Idle)\% Processor Time                       166.151              400.930               69.159 \\{servername}\    

It looks like the Average System Idle CPU Utilization is actually the non-Idle CPU util

Idle: 166/4=41.5
                System (4*100-Idle): (400-166)=234, 234/4=58.5

I think the Bottleneck Analysis report form needs to be changed to remove “Idle” from this. Historically, this always showed overall System CPU and not Idle CPU, so not sure when this got changed and if it was intentional.

**Comment by PiJoCoder** [comment]
The Bottleneck analysis pulls its data from the sys.dm_os_ring_buffers DMV captured via PSSDIAG. Problem is that the CPU numbers are not always accurate in that DMV. The DMV is deprecated and no longer supported based on the documentation. Longer-term the graph in this view should be changed to pull data from Perfmon counters if avaialble, because it is not always trustworthy.

**Comment by NathanMSFT** [comment]
@PiJoCoder - all I was referring to with this request was to remove the word "Idle" because it is misleading. That number (its accuracy notwithstanding) is for "Average System CPU Utilization" not "Average System **Idle** CPU Utilization".

**Comment by PiJoCoder** [comment]
> @PiJoCoder - all I was referring to with this request was to remove the word "Idle" because it is misleading. That number (its accuracy notwithstanding) is for "Average System CPU Utilization" not "Average System **Idle** CPU Utilization".

Got it. We can remove or rename so its heading reflects the proper number. Does that work? Or do you prefer it be removed entirely?

**Comment by NathanMSFT** [comment]
Yes, just removing the word "Idle" to avoid the confusion. Thanks!

**Comment by PiJoCoder** [comment]
You got it! Also just verified the expression which is exactly what you calculated:
=CInt (100-Avg(Fields!system_idle_cpu.Value, "DataSet_SQL_CPU")) & "%"
