### ISSUE TITLE
Best Practice Analyzer: Needs update/revamp for the rules that provide suggestions server configuration

### ISSUE THREAD

**Issue by suresh-kandoth** [microsoft/SqlNexus#90]
The rules are baked into the script PerfStatsAnalysis.sql
Look for warnings like:
'NonDefault_sp_configure', 'Some sp_configure values are not set to default.', 'Non Default values do not necessarily mean issues.  But please review Server Configuration report to make sure they are as intended

**Comment by PiJoCoder** [comment]
Config options to call out:

- Max Server Memory  - if unbound , call it out
- MAX Dop
- Priority boost
- optimizer for ad-hoc workloads - turn it on
- Affinity
- Lightweight pooling

**Comment by PiJoCoder** [comment]
Warnings produced after building these

![image](https://user-images.githubusercontent.com/23519517/208230726-673b3470-9b29-4790-aa03-9a0f035d6f63.png)
