### ISSUE TITLE
GAC Error - Microsoft.ReportViewer.Processing.ObjectModel Version 13.0.0.0

### ISSUE THREAD

**Issue by PrometheusRising1** [microsoft/SqlNexus#93]
"Unable to install or run the application.  The application requires that assembly Microsoft.ReportViewer.Processing.ObjectModel Version 13.0.0.0 be installed in the Global Assembly Cache (GAC) first.  More information on this system update can be found by visiting the site here."

Site "here" links to the old codeplex site.  

Do you know the origin of this error and can you include a newer link for the error message in the next version?

**Comment by PrometheusRising1** [comment]
Installation doc should be referenced in the Quickstart - it looks like you simply try to run RML and the Setup.exe for SQLNexus

**Comment by PiJoCoder** [comment]
@PrometheusRising1 thank you for raising this and sorry for delay. 
So in general this error indicates that one the prerequisites for SQL Nexus is a ReportViewer control. We had someone [report ](https://github.com/microsoft/SqlNexus/issues/99) that the wrong link was provided to the download of ReportViewer. You can get the control here -> https://www.microsoft.com/en-us/download/details.aspx?id=56833. Just download  **ENU\x86\ReportViewer.msi**

Yes, I found a couple of old CodePlex reference link in the code - one of the reports and changed them. In the next version there will be no more references to CodePlex. Thank you!

I cannot find the origins of the error - how did you receive it? Did you just navigate to one of the reports and received it then? That would be the only logical place.

I found a function CheckReportViewer() but its code is commented out so it does not do much. I wonder if we can revive this code and check for the mininum required version. We'll make a decision on that and publish in next build. 

Thank you again

**Comment by PiJoCoder** [comment]
Reviewed the CheckReportViewer() function further. It was designed to check a specific version of an assembly. Will leave that commented out for now. 
Also, we will be introducing a Powershell file to install all the prerequisites automatically so you don't have to worry about those manually.

**Comment by PrometheusRising1** [comment]
Thank you very much for looking into this! Looking forward to the new version!

**Comment by PiJoCoder** [comment]
Actually @PrometheusRising1 , you can grab the Powershell file from this working branch we are checking into. 

https://github.com/microsoft/SqlNexus/tree/Fixorama_ToddJo_Jan2021/Setup-Related
