### ISSUE TITLE
Issue importing XEL files

### ISSUE THREAD

**Issue by KlausLadegaard** [microsoft/SqlNexus#96]
Keep getting this when importing files from my busy server  (several source servers - same error)

08/24/20 09:39:04.688 [0X00001A54] Events Read: 2475000 Queued: 73 Processed/sec: 7671
08/24/20 09:39:06.273 [0X000004C8] ERROR: Event runtime check:  Detected missing column [object_name] in event [sp_cache_remove] at event sequence 22056625
08/24/20 09:39:06.393 [0X000004C8] ERROR: Event sp_cache_remove
08/24/20 09:39:18.954 [0X00001A54] *** ERROR: Reader encountered operating system error 0x8007000D (The data is invalid) State: 0  Global Seq: 0
08/24/20 09:39:18.956 [0X00001A54] Reads completed - Global Error Status 0xffffffe7
08/24/20 09:39:18.958 [0X00001A54] Signaling worker threads to complete final actions.
08/24/20 09:39:18.962 [0X00001A54] Waiting for the worker threads to complete final actions.
08/24/20 09:39:19.413 [0X00001A54] Performing general cleanup actions.
08/24/20 09:39:19.413 [0X00001A54] Total Events Processed: 2757638
08/24/20 09:39:19.415 [0X00001A54]  Total Events Filtered: 29693
08/24/20 09:39:19.416 [0X00001A54] *******************************************************************************
* ReadTrace encountered one or more ERRORS. An error condition typically      *
* stops processing early and the ReadTrace output may be unusable.            *
* Review the log file for details.                                            *
*******************************************************************************
08/24/20 09:39:19.418 [0X00001A54] ***** ReadTrace exit code: -25
08/24/20 09:39:19.419 [0X00001A54]  INFO: Max set-aside XEL event hash table entry count: 300051
08/24/20 09:39:19.419 [0X00001A54] ERROR: Unexpected outcome, cached XEL events still found on the set-aside list.  Output may not be complete.  This could be due to CTRL+C or other error conditon.

Stopping PSSDIAG with ctrl+c

**Comment by KlausLadegaard** [comment]
I have now isolated it to file, I can open in SSMS and LINQ but not with SQLNexus

I tested with a simple READTRACE -I<file>
I will provide data file if RML team want it, but not to public

**Comment by PiJoCoder** [comment]
@KlausLadegaard thank you for reporting this! 
This is more an issue with ReadTrace than SQLNexus but let me see if we can take a stab. Based on the error message 

08/24/20 09:39:19.419 [0X00001A54] ERROR: Unexpected outcome, cached XEL events still found on the set-aside list. Output may not be complete. This could be due to CTRL+C or other error conditon.

...it appears that while ReadTrace was trying to process the file it found some unexpected event occurred - like perhaps the XEL collection was interrupted suddenly. I can surmise that the "set-aside list" contains events that perhaps had a starting "part" and then a "finishing" part and the latter was not found due to an abrupt stop.  Was the data collection done via PSSDIAG/SQLDIAG and was it interrupted suddently via multiple CTRL+C events?

@suresh-kandoth , do you have any other thoughts on this?

**Comment by KlausLadegaard** [comment]
No, just that it happenes often


Hent Outlook til Android

**Comment by naveenrpendli** [comment]
@KlausLadegaard are you using the 6.0.0.8 version ? or the current one. I'm having issue in importing the XEL files into the Nexus. When I go to the output folder Nexus don't recognize the files at all. If you have any documentation for the XEL file or something that will be a huge help to me to start using Nexus. 

Thanks
Naveen

**Comment by suresh-kandoth** [comment]
Are you capturing this event sp_cache_remove in the XEL files?
_08/24/20 09:39:06.393 [0X000004C8] ERROR: Event sp_cache_remove_

Does this event have the field [object_name] added to the collection?
_08/24/20 09:39:06.273 [0X000004C8] ERROR: Event runtime check: Detected missing column [object_name] in event [sp_cache_remove] at event sequence 22056625_

Several fields are marked as required for the processing and aggregation. So if those fields are missing, then ReadTrace will not import.

**Comment by PiJoCoder** [comment]
Closing for now. Please reopen if needed.

**Comment by WinterIssue** [comment]
Got the same problem. SQL Server 2016 SP2.

ERROR: Event runtime check:  Detected missing column [object_name] in event [sp_cache_remove] at event sequence 155472
12/03/21 10:12:43.978 [0X0000428C] ERROR: Event sp_cache_remove

XML starts like this
`
<event name="sp_cache_remove" package="sqlserver" timestamp="2021-12-02T00:38:19.410Z">
  <data name="object_type">
    <value>20816</value>
    <text>PREPARED</text>
  </data>
  <data name="database_id">
    <value>6</value>
  </data>
  <data name="object_id">
    <value>973328245</value>
  </data>
  <data name="remove_method">
    <value>1</value>
    <text>Compplan Remove</text>
  </data>
  <data name="object_name">
    <value />
  </data>
  <data name="cached_text">
    <value />
  </data>
  <data name="database_name">
    <value />
  </data>
  <data name="plan_handle">
    <value />...`
